### ISSUE TITLE
Query: Diagramming tool used for overview diagram

### ISSUE THREAD

**Issue by vashnt707** [devmentors/Pacco#12]
**Not an issue**

May I know what is the diagramming tool used for creating the overview diagram? Looks great and less serious

**Comment by remotenode** [comment]
+++

**Comment by Dakraeth2** [comment]
+++

**Comment by spetz** [comment]
https://excalidraw.com :)

**Comment by spetz** [comment]
Simply [draw.io](http://draw.io) :)
