### ISSUE TITLE
Project Structure Help

### ISSUE THREAD

**Issue by mumby0168** [devmentors/Pacco#4]
Hi guys not sure this is the best place for this but how do you get the project structure for your microsercices inside a .sln using the folder name/src/ (other dlls)

**Comment by ahp98** [comment]
Are you trying to run in visual studio?

**Comment by mumby0168** [comment]
I was recently moved over to rider but struggel to get the structure like this

**Comment by mumby0168** [comment]
I think I have managed to get it now in rider doesnt seem that visual studio likes to map solution folders to real ones for some reason.

**Comment by ahp98** [comment]
Yea for that is made directories inside vs itself but it's easier to use vs code totally
